# Generated by Django 4.2.5 on 2023-10-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('vertientes', models.PositiveIntegerField(default=0)),
                ('ubicación', models.CharField(max_length=200, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'comunidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='vertiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('ubicación', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('caudal', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('conductividad', models.IntegerField(default=0)),
                ('turbiedad', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('humedad', models.IntegerField(default=0)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.comunidad')),
            ],
            options={
                'verbose_name': 'Vertiente',
                'verbose_name_plural': 'Vertientes',
                'db_table': 'vertiente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField(default=0)),
                ('ubicación', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=False)),
                ('vertiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.vertiente')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'db_table': 'Kit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caudal', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('conductividad', models.IntegerField(default=0)),
                ('turbiedad', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('humedad', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('vertiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.vertiente')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'db_table': 'datos',
                'ordering': ['id'],
            },
        ),
    ]
